# https://github.com/actions/stale
name: Mark stale issues and pull requests
  schedule:
    - cron: '* * * * *' # once a day at 2pm
jobs:
  stale:
    permissions:
      issues: write # for commenting on an issue and editing labels
      pull-requests: write # for commenting on a PR and editing labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # timing
          days-before-stale: 0 # 2 weeks of inactivity
          days-before-close: 1 # 2 more weeks of inactivity
          # labels to watch for, add, and remove
          only-labels: 'pending info' # only mark issues/PRs as stale if they have this label
          labels-to-remove-when-unstale: 'pending info' # remove label when unstale -- should be manually added back if information is insufficient
          # automated messages to issue/PR authors
          stale-issue-message: 'This issue is marked as stale because it has been open 60 days with no activity. Remove pending info label or comment or this will be closed in 7 days.'
          stale-pr-message: 'This pull request is marked as stale because it has been open 60 days with no activity. Remove pending info label or comment or this will be closed in 7 days.'
          close-issue-message: 'This issue has been closed due to inactivity and lack of information.If you still encounter this issue, please add the requested information and re-open.'
          close-pr-message: 'This PR has been closed due to inactivity and lack of changes.If you would like to still work on this PR, please address the review comments and re-open.'
  
